# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Import_Data.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Import_Window(object):
    def setupUi(self, Import_Window):
        Import_Window.setObjectName("Import_Window")
        Import_Window.resize(1000, 600)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        Import_Window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Import_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(250, 60, 730, 260))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setObjectName("textEdit")
        self.Open_Main = QtWidgets.QPushButton(self.centralwidget)
        self.Open_Main.setGeometry(QtCore.QRect(310, 400, 300, 60))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Open_Main.setFont(font)
        self.Open_Main.setObjectName("Open_Main")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 221, 141))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.find_files_btn1 = QtWidgets.QPushButton(self.groupBox)
        self.find_files_btn1.setGeometry(QtCore.QRect(10, 40, 200, 32))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.find_files_btn1.setFont(font)
        self.find_files_btn1.setObjectName("find_files_btn1")
        self.reload_btn = QtWidgets.QPushButton(self.groupBox)
        self.reload_btn.setGeometry(QtCore.QRect(10, 90, 200, 32))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.reload_btn.setFont(font)
        self.reload_btn.setObjectName("reload_btn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 221, 141))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.find_files_btn2 = QtWidgets.QPushButton(self.groupBox_2)
        self.find_files_btn2.setGeometry(QtCore.QRect(10, 40, 200, 32))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.find_files_btn2.setFont(font)
        self.find_files_btn2.setObjectName("find_files_btn2")
        self.append_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.append_btn.setGeometry(QtCore.QRect(10, 90, 200, 32))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.append_btn.setFont(font)
        self.append_btn.setObjectName("append_btn")
        self.groupBox.raise_()
        self.textEdit.raise_()
        self.Open_Main.raise_()
        self.groupBox_2.raise_()
        Import_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Import_Window)
        self.statusbar.setObjectName("statusbar")
        Import_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Import_Window)
        #self.Open_Main.clicked.connect(Import_Window.openmain)
        self.find_files_btn1.clicked.connect(Import_Window.find_files)
        self.find_files_btn2.clicked.connect(Import_Window.find_files)
        #self.reload_btn.clicked.connect(Import_Window.reload_files)
        #self.append_btn.clicked.connect(Import_Window.append_files)
        QtCore.QMetaObject.connectSlotsByName(Import_Window)
        Import_Window.setTabOrder(self.find_files_btn1, self.reload_btn)
        Import_Window.setTabOrder(self.reload_btn, self.textEdit)

    def retranslateUi(self, Import_Window):
        _translate = QtCore.QCoreApplication.translate
        Import_Window.setWindowTitle(_translate("Import_Window", "导入数据"))
        self.Open_Main.setText(_translate("Import_Window", "打开主界面"))
        self.groupBox.setTitle(_translate("Import_Window", "重新读取所有数据"))
        self.find_files_btn1.setText(_translate("Import_Window", "1.浏览选择数据文件"))
        self.reload_btn.setText(_translate("Import_Window", "2.读取数据文件"))
        self.groupBox_2.setTitle(_translate("Import_Window", "加入新数据"))
        self.find_files_btn2.setText(_translate("Import_Window", "1.浏览选择数据文件"))
        self.append_btn.setText(_translate("Import_Window", "2.读取数据文件"))

