# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Import_Data.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Import_Window(object):
    def setupUi(self, Import_Window):
        Import_Window.setObjectName("Import_Window")
        Import_Window.resize(800, 601)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        Import_Window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Import_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 200, 491, 361))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setObjectName("textEdit")
        self.Open_Main = QtWidgets.QPushButton(self.centralwidget)
        self.Open_Main.setGeometry(QtCore.QRect(530, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        self.Open_Main.setFont(font)
        self.Open_Main.setObjectName("Open_Main")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 221, 141))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 200, 32))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton2.setGeometry(QtCore.QRect(10, 90, 200, 32))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 40, 221, 141))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 30, 200, 32))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton2_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton2_4.setGeometry(QtCore.QRect(10, 90, 200, 32))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton2_4.setFont(font)
        self.pushButton2_4.setObjectName("pushButton2_4")
        self.groupBox.raise_()
        self.textEdit.raise_()
        self.Open_Main.raise_()
        self.groupBox_2.raise_()
        Import_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Import_Window)
        self.statusbar.setObjectName("statusbar")
        Import_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Import_Window)
        #self.Open_Main.clicked.connect(Import_Window.openmain)
        QtCore.QMetaObject.connectSlotsByName(Import_Window)
        Import_Window.setTabOrder(self.pushButton, self.pushButton2)
        Import_Window.setTabOrder(self.pushButton2, self.textEdit)

    def retranslateUi(self, Import_Window):
        _translate = QtCore.QCoreApplication.translate
        Import_Window.setWindowTitle(_translate("Import_Window", "导入数据"))
        self.Open_Main.setText(_translate("Import_Window", "打开主界面"))
        self.groupBox.setTitle(_translate("Import_Window", "重新读取所有数据"))
        self.pushButton.setText(_translate("Import_Window", "1.浏览选择数据文件"))
        self.pushButton2.setText(_translate("Import_Window", "2.读取数据文件"))
        self.groupBox_2.setTitle(_translate("Import_Window", "加入新数据"))
        self.pushButton_4.setText(_translate("Import_Window", "1.浏览选择数据文件"))
        self.pushButton2_4.setText(_translate("Import_Window", "2.读取数据文件"))

