# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index_trend_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_index_trend_dialog(object):
    def setupUi(self, index_trend_dialog):
        index_trend_dialog.setObjectName("index_trend_dialog")
        index_trend_dialog.resize(1200, 600)
        self.comboBox_3 = QtWidgets.QComboBox(index_trend_dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(100, 100, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(index_trend_dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_6 = QtWidgets.QComboBox(index_trend_dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(100, 300, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_3 = QtWidgets.QLabel(index_trend_dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(index_trend_dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(index_trend_dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 250, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_4 = QtWidgets.QComboBox(index_trend_dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(100, 200, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(index_trend_dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(100, 350, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label = QtWidgets.QLabel(index_trend_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(index_trend_dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_5 = QtWidgets.QComboBox(index_trend_dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(100, 250, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(index_trend_dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 50, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(index_trend_dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(index_trend_dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBox_8 = QtWidgets.QComboBox(index_trend_dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(100, 150, 120, 30))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")

        self.retranslateUi(index_trend_dialog)
        QtCore.QMetaObject.connectSlotsByName(index_trend_dialog)

    def retranslateUi(self, index_trend_dialog):
        _translate = QtCore.QCoreApplication.translate
        index_trend_dialog.setWindowTitle(_translate("index_trend_dialog", "煤种质量变化趋势"))
        self.comboBox_3.setItemText(0, _translate("index_trend_dialog", "所有"))
        self.comboBox_3.setItemText(1, _translate("index_trend_dialog", "1985-1990"))
        self.comboBox_3.setItemText(2, _translate("index_trend_dialog", "1991-1995"))
        self.comboBox_3.setItemText(3, _translate("index_trend_dialog", "1996-1998"))
        self.comboBox_3.setItemText(4, _translate("index_trend_dialog", "1999-2002"))
        self.comboBox_3.setItemText(5, _translate("index_trend_dialog", "2003-2005"))
        self.comboBox_3.setItemText(6, _translate("index_trend_dialog", "2006-2010"))
        self.comboBox_3.setItemText(7, _translate("index_trend_dialog", "2011-2015"))
        self.comboBox_3.setItemText(8, _translate("index_trend_dialog", "2016至今"))
        self.label_5.setText(_translate("index_trend_dialog", "热强度"))
        self.comboBox_6.setItemText(0, _translate("index_trend_dialog", "所有"))
        self.comboBox_6.setItemText(1, _translate("index_trend_dialog", "特高"))
        self.comboBox_6.setItemText(2, _translate("index_trend_dialog", "高"))
        self.comboBox_6.setItemText(3, _translate("index_trend_dialog", "中"))
        self.comboBox_6.setItemText(4, _translate("index_trend_dialog", "低"))
        self.comboBox_6.setItemText(5, _translate("index_trend_dialog", "特低"))
        self.label_3.setText(_translate("index_trend_dialog", "煤种"))
        self.label_8.setText(_translate("index_trend_dialog", "灰分"))
        self.label_7.setText(_translate("index_trend_dialog", "硬度"))
        self.comboBox_4.setItemText(0, _translate("index_trend_dialog", "所有"))
        self.comboBox_4.setItemText(1, _translate("index_trend_dialog", "A级"))
        self.comboBox_4.setItemText(2, _translate("index_trend_dialog", "B级"))
        self.comboBox_4.setItemText(3, _translate("index_trend_dialog", "C级"))
        self.comboBox_7.setItemText(0, _translate("index_trend_dialog", "所有"))
        self.comboBox_7.setItemText(1, _translate("index_trend_dialog", "特高"))
        self.comboBox_7.setItemText(2, _translate("index_trend_dialog", "高"))
        self.comboBox_7.setItemText(3, _translate("index_trend_dialog", "中"))
        self.comboBox_7.setItemText(4, _translate("index_trend_dialog", "低"))
        self.comboBox_7.setItemText(5, _translate("index_trend_dialog", "特低"))
        self.label.setText(_translate("index_trend_dialog", "煤种筛选条件"))
        self.label_9.setText(_translate("index_trend_dialog", "硫分"))
        self.comboBox_5.setItemText(0, _translate("index_trend_dialog", "所有"))
        self.comboBox_5.setItemText(1, _translate("index_trend_dialog", "硬煤"))
        self.comboBox_5.setItemText(2, _translate("index_trend_dialog", "半硬优"))
        self.comboBox_5.setItemText(3, _translate("index_trend_dialog", "半硬"))
        self.comboBox_5.setItemText(4, _translate("index_trend_dialog", "半软"))
        self.comboBox_5.setItemText(5, _translate("index_trend_dialog", "软煤"))
        self.comboBox_2.setItemText(0, _translate("index_trend_dialog", "所有"))
        self.comboBox_2.setItemText(1, _translate("index_trend_dialog", "焦煤"))
        self.comboBox_2.setItemText(2, _translate("index_trend_dialog", "肥煤"))
        self.comboBox_2.setItemText(3, _translate("index_trend_dialog", "气煤"))
        self.comboBox_2.setItemText(4, _translate("index_trend_dialog", "1/3焦煤"))
        self.comboBox_2.setItemText(5, _translate("index_trend_dialog", "瘦煤"))
        self.label_4.setText(_translate("index_trend_dialog", "数据年份"))
        self.label_6.setText(_translate("index_trend_dialog", "煤质分级"))
        self.comboBox_8.setItemText(0, _translate("index_trend_dialog", "所有"))
        self.comboBox_8.setItemText(1, _translate("index_trend_dialog", "特等"))
        self.comboBox_8.setItemText(2, _translate("index_trend_dialog", "优质"))
        self.comboBox_8.setItemText(3, _translate("index_trend_dialog", "中等"))
        self.comboBox_8.setItemText(4, _translate("index_trend_dialog", "一般"))

